console.log(console)
console.error("Hii this is error message")
console.assert()
console.assert(5>53)
console.assert(53>5)
console.clear()
console.table()
console.warn("please dont do this")
console.info("Hey this is an important info")
console.time("a")
console.timeEnd("a")
